version: '3.4'
services:
  bookshop:
    build:
      context: .
      target: dev
    volumes:
      - ./:/app
    command: npm run start:dev
    ports:
      - '3000:300'
    entrypoint:
      - MONGO_URL=mongodb+srv://developer:IZ2acz3iWdpmw7Im@nestdevopscluster.gdfyt.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
